### ISSUE TITLE
How would I add fields based on columns?

### ISSUE THREAD

**Issue by jerrac** [lifepillar/csv2keepassxml#2]
In my csv I have an ip address field that I would like to use as a custom field in my KeeWeb file. 

Would I add a new ```opts.on``` block? Something like:

```ruby
opts.on("-F", "--field NUM", Integer, "Column number of custom field") do |o|
    options[:field] = o
  end
```
How would I tell it what to name the field? Or would I need to just add a custom ```opts.on``` block for each custom field I want to add?

**Comment by lifepillar** [comment]
>How would I tell it what to name the field?

The column header would become the field's name. I'll try to implement support for custom fields soon.

**Comment by lifepillar** [comment]
Please try the current master. There is a new option to specify custom fields. For instance, if your custom fields are at column 7 and 10, then you use:

```
./csv2keepassxml -F 7,10 …
```

where `…` are the remaining options. If the CSV has a header, the custom fields's names are taken from the header. Otherwise, they are named `CustomField1`, `CustomField2`, etc…

**Important:** make sure you have a backup of your files, this feature has not been tested much!

**Comment by jerrac** [comment]
The ```CustomField1```, ```CustomField2``` autonaming does not work.

```
./csv2keepassxml --dbname testconvert -p 7 -n 8 -t 2 -u 6 -U 3 -F 2,3,4,5,6 -T 4,5 --tag-separator / --no-header passwordnoheader.csv
File exists: ./passwordsnoheader.xml
Overwrite (y/n)?y
./csv2keepassxml:187:in `block in <main>': undefined method `header_row?' for #<Array:0x000000021f75a0> (NoMethodError)
	from /usr/lib/ruby/2.3.0/csv.rb:1748:in `each'
	from /usr/lib/ruby/2.3.0/csv.rb:1131:in `block in foreach'
	from /usr/lib/ruby/2.3.0/csv.rb:1282:in `open'
	from /usr/lib/ruby/2.3.0/csv.rb:1130:in `foreach'
	from ./csv2keepassxml:185:in `<main>'
```

If I add a header row, and don't use the ```--no-header``` flag, it works just fine.

**Comment by jerrac** [comment]
btw, thanks for adding this and the tags feature! :D

**Comment by lifepillar** [comment]
Please try the current master, which has a fix for the `--no-header` error.

**Comment by jerrac** [comment]
Yep! It's fixed. Thanks!
