### ISSUE TITLE
How can I add tags from multiple columns?

### ISSUE THREAD

**Issue by jerrac** [lifepillar/csv2keepassxml#3]
In my csv file, I'd like columns 4 and 5 to become tags on each entry.

I see the ```  s += "<Tags/>"``` line in the xml_entry function. I'm guessing I would modify that line somehow to add the tags. I think I'd add an option to the command line with a list of column numbers to use, and then something like:

```ruby
  s += "<Tags>"
  # code to add each tag here. would it just be a comma separated list, or is the sub xml element? 
  s += "</Tags>"
```

Any suggestions on how to make that happen?

**Comment by lifepillar** [comment]
>In my csv file, I'd like columns 4 and 5 to become tags on each entry.

How are those columns to be formatted? Would they contain one tag each?

>would it just be a comma separated list, or is the sub xml element? 

Looking at the XML export from MacPass, tags appear to be semicolon-separated strings between `<Tags>`:

```
<Tags>tagone;tagtwo;tagthree</Tags>
```

>Any suggestions on how to make that happen?

By asking, as you did :) I'll give it a shot soon.

**Comment by jerrac** [comment]
In my specific case, they are formated as strings and only have one tag each. 

If it isn't too difficult, I'd add an option to set a custom tag delimiter. That way a column that had a set of tags separated by commas, semi-colons, or spaces could be parsed.

Thanks!

**Comment by lifepillar** [comment]
Please try the current master. There is a new `-T` (`--tags`) option to specify a list of columns to be interpreted as tags. Each column may contain zero or more tags, separated by a semicolon by default. If the tag separator is different, use `--tag-separator` (a regexp in general).

For instance, if columns 4 and 5 contain tags, use:

```
csv2keepassxml -T 4,5 …
```

(where `…` are the remaining options).

**Comment by jerrac** [comment]
```
./csv2keepassxml --dbname testconvert -p 7 -n 8 -t 2 -u 6 -U 3 --no-header -g 4 -T 4,5 passwords.csv
File exists: ./password.xml
Overwrite (y/n)?y
./csv2keepassxml:187:in `block in <main>': undefined method `header_row?' for #<Array:0x00000002554518> (NoMethodError)
	from /usr/lib/ruby/2.3.0/csv.rb:1748:in `each'
	from /usr/lib/ruby/2.3.0/csv.rb:1131:in `block in foreach'
	from /usr/lib/ruby/2.3.0/csv.rb:1282:in `open'
	from /usr/lib/ruby/2.3.0/csv.rb:1130:in `foreach'
	from ./csv2keepassxml:185:in `<main>'

```
My csv file does not have a header row.

**Comment by jerrac** [comment]
*coughs* ```--no-header``` *coughs*

**Comment by jerrac** [comment]
I created a version with a header row, and it worked just fine after I removed my --no-header flag...

**Comment by lifepillar** [comment]
Ok, the current master should fix the error with `--no-header`. Sorry for the trouble.

**Comment by jerrac** [comment]
Yep! It's fixed. Thanks!
