### ISSUE TITLE
Passwords not displayed as dots on import

### ISSUE THREAD

**Issue by jerrac** [lifepillar/csv2keepassxml#4]
After importing an xml file generated by csv2keepassxml, the password field displays the text of the password instead of the normal dots.

Steps to reproduce:

- Generate xml file.
- Import xml file into KeeWeb.
- View any entry, the password is visible without you clicking in the field.

This is also true if you save the file as a kdbx file and then reopen it. I even made sure to remove it from the initial list of available files you get when you don't have any open.

I did some searching and found https://github.com/keeweb/keeweb/issues/85 Looking at the raw xml, the password value looks like this:

```xml
<String>
  <Key>Password</Key>
  <Value ProtectedInMemory="True">password</Value>
</String>
```
Which sounds like what that issue was suggesting needed to be done. 

So, yeah, I'm not sure if this is something caused by the convert and import process, or a bug in KeeWeb. If you think it's keeweb, let me know and I'll open an issue there.

App info:

KeeWeb v1.3.3 (52701af, 2016-09-20)
Environment: electron v1.3.3
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/1.3.3 Chrome/52.0.2743.82 Electron/1.3.3 Safari/537.36

I'm on Ubuntu 16.04.

**Comment by lifepillar** [comment]
Thanks for the detailed report. There was a typo: it's not `ProtectedInMemory`, but `ProtectInMemory`. I have fixed that.


Btw, did you get a `TypeError: Cannot read property 'password' of undefined` error from KeeWeb?

**Comment by jerrac** [comment]
Yep, it's fixed. Thanks!

I did not see any errors output from the KeyWeb app at all. Where would I have seen them?

**Comment by lifepillar** [comment]
Never mind. That appears like [a bug in KeeWeb 1.5.4](https://github.com/keeweb/keeweb/issues/694) (you may not see it because you are using an older version).

**Comment by jerrac** [comment]
Ah. :)
