### ISSUE TITLE
cannot launch csv2keeoassxml because of dependencies

### ISSUE THREAD

**Issue by wellumies** [lifepillar/csv2keepassxml#5]
htmlentities is not found by Ruby. Should there be some info on which package and how to install it before running this?

**Comment by lifepillar** [comment]
Thanks for pointing that out. I have updated the Readme to reflect the needed requirement.

**Comment by wellumies** [comment]
Sorry for this. Took me Google and 15 seconds to fix

**Comment by lifepillar** [comment]
Never mind. Not making requirements explicit is never a good idea.
